# Generated by Django 5.2.4 on 2026-03-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auric1', '0005_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
