# Generated by Django 5.2.4 on 2026-03-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auric1', '0006_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
